<?php
declare(strict_types=1);
require_once __DIR__.'/lib/ResearchDb.php';
require_once __DIR__.'/lib/FirmwareImporter.php';
require_once __DIR__.'/lib/FirmwareCompare.php';
require_once __DIR__.'/lib/PrinterProfiles.php';
require_once __DIR__.'/lib/FirmwareParameterExtractor.php';
require_once __DIR__.'/lib/ProjectExporter.php';
require_once __DIR__.'/lib/StockFirmwareBuilder.php';
$private=getenv('PRIVATE_DIR')?:dirname(__DIR__,2).'/private';$db=ResearchDb::open($private);$msg='';$err='';
try {
 if($_SERVER['REQUEST_METHOD']==='POST' && isset($_FILES['firmware'])){
   $id=(new FirmwareImporter($db,$private))->import($_FILES['firmware']['tmp_name'],$_FILES['firmware']['name'],trim($_POST['notes']??''));
   $project=FirmwareParameterExtractor::projectData($db,$id,(string)($_POST['printer_model']??'auto'),trim((string)($_POST['project_name']??'')));
   $project['profile_id']=0;
   $profileId=PrinterProfiles::save($db,$project);
   $msg="Imported package #$id and created research project #$profileId";
   $_GET['profile']=$profileId;
 }
 if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='export_project'){
   $path=ProjectExporter::export($db,(int)($_POST['profile_id']??0),$private);
   header('Content-Type: application/json');header('Content-Disposition: attachment; filename="'.basename($path).'"');readfile($path);exit;
 }
 if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='download_official'){
   $pid=(int)($_POST['package_id']??0);$q=$db->prepare('SELECT original_name,stored_name FROM firmware_packages WHERE id=?');$q->execute([$pid]);$pkg=$q->fetch(PDO::FETCH_ASSOC);if(!$pkg)throw new RuntimeException('Firmware package not found');
   $path=rtrim($private,'/').'/bambu/firmware/'.$pkg['stored_name'];if(!is_file($path))throw new RuntimeException('Archived OTA file missing');
   header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.basename($pkg['original_name']).'"');readfile($path);exit;
 }
 if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='refill_profile'){
   $profileId=(int)($_POST['profile_id']??0);
   $model=(string)($_POST['refill_model']??'auto');
   $overwrite=($_POST['overwrite_known']??'0')==='1';
   $id=FirmwareParameterExtractor::refillProfile($db,$profileId,$model,$overwrite);
   $msg=$overwrite?'Re-extracted and refreshed project parameters':'Auto-filled blank project parameters';
   $_GET['profile']=$id;
 }
 if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='generate_stock_probe'){
   $path=StockFirmwareBuilder::generate($db,(int)($_POST['profile_id']??0),$_POST,$private);
   header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.basename($path).'"');readfile($path);exit;
 }
 if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='save_profile'){
   if(($_POST['save_mode']??'update')==='copy') $_POST['profile_id']=0;
   $id=PrinterProfiles::save($db,$_POST);$msg="Saved Bambu research project #$id";$_GET['profile']=$id;
 }
} catch(Throwable $e){$err=$e->getMessage();}
$packages=$db->query('SELECT p.*,(SELECT COUNT(*) FROM firmware_components c WHERE c.package_id=p.id) component_count FROM firmware_packages p ORDER BY imported_at DESC')->fetchAll(PDO::FETCH_ASSOC);
$boards=$db->query('SELECT * FROM boards ORDER BY printer_code,board_role,board_revision')->fetchAll(PDO::FETCH_ASSOC);
$hardware=$db->query('SELECT * FROM hardware_components ORDER BY printer_code,board_role,component_role')->fetchAll(PDO::FETCH_ASSOC);
$connectors=$db->query('SELECT * FROM board_connectors ORDER BY printer_code,board_role,connector_name')->fetchAll(PDO::FETCH_ASSOC);
$profiles=PrinterProfiles::list($db);$profileId=(int)($_GET['profile']??0);$profile=$profileId?PrinterProfiles::get($db,$profileId):null;
if(!$profile){$profile=array_merge(['id'=>0,'printer_code'=>'','profile_name'=>''],PrinterProfiles::DEFAULTS);}
$evidence=$profile['id']?PrinterProfiles::evidence($db,(int)$profile['id']):[];
$readiness=PrinterProfiles::readiness($db,$profile);$stockStatus=StockFirmwareBuilder::status($db,$profile);
$compare=[];$aid=(int)($_GET['a']??0);$bid=(int)($_GET['b']??0);if($aid&&$bid&&$aid!==$bid)$compare=FirmwareCompare::run($db,$aid,$bid);
function h($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function val($p,$k){return h($p[$k]??'');} function checked($p,$k){return !empty($p[$k])?'checked':'';}
function num($p,$k,$min='',$max='',$step='any'){echo '<input type="number" name="'.h($k).'" value="'.val($p,$k).'"'.($min!==''?' min="'.$min.'"':'').($max!==''?' max="'.$max.'"':'').' step="'.$step.'">';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bambu Research — HotFetched</title><link rel="stylesheet" href="assets/research.css"></head><body><main>
<div class="topbar"><a class="brand" href="/"><span class="brand-text"><span class="accent">Hot</span>Fetched</span></a><span class="sub">Bambu firmware research</span></div>
<header><div><h1>Bambu A1 mini Firmware Lab</h1><p>Create local projects for the installed A1 mini mainboard and toolhead, preserve official OTAs, build RAM probes, and progress toward evidence-backed custom firmware.</p></div><div class="badge">Stock hardware target</div></header>
<?php if($msg):?><div class="ok"><?=h($msg)?></div><?php endif;if($err):?><div class="err"><?=h($err)?></div><?php endif;?>
<nav class="tabs"><a href="#parameters">Parameters</a><a href="#pipeline">Build pipeline</a><a href="#stock-builder">Stock-board creator</a><a href="#hardware">Hardware lab</a><a href="#firmware">Firmware library</a><a href="#compare">Compare</a><a href="#boards">Boards</a></nav>
<section id="import" class="import-panel"><div class="section-title"><div><h2>Import Bambu firmware ZIP</h2><p class="muted">Upload the untouched offline OTA downloaded from Bambu Lab. HotFetched archives it, inventories the boards/components, and opens an editable project populated with known model specifications and firmware evidence.</p></div><a class="btn" href="https://bambulab.com/en/support/firmware-download/a1-mini" target="_blank" rel="noopener">Bambu firmware downloads ↗</a></div>
<form method="post" enctype="multipart/form-data" class="import-form">
<label>Firmware ZIP<input type="file" name="firmware" accept=".zip,application/zip" required></label>
<label>Printer model<select name="printer_model"><option value="auto">Auto-detect platform</option><option value="a1-mini">A1 mini</option><option value="a1">A1</option><option value="p1p">P1P</option><option value="p1s">P1S</option><option value="x1c">X1 Carbon</option><option value="h2d">H2D</option></select></label>
<label>Project name<input name="project_name" placeholder="A1 mini — firmware 01.08.00"></label>
<label>Import notes<input name="notes" placeholder="Downloaded from Bambu Lab"></label>
<div class="actions"><button class="btn primary">Import ZIP & create project</button></div></form>
<p class="muted small">Original packages remain unchanged at <code>$PRIVATE_DIR/bambu/firmware/&lt;sha256&gt;.zip</code>. Unknown low-level parameters remain blank instead of using unsafe Marlin defaults.</p></section>
<section id="parameters"><div class="section-title"><div><h2>Project parameters</h2><p class="muted">The same machine, geometry, motion, driver, and thermal workflow used by HotFetched projects for Marlin, Klipper, and RepRapFirmware.</p></div><form method="get" class="compact"><label>Open project<select name="profile" onchange="this.form.submit()"><option value="">＋ New Bambu project</option><?php foreach($profiles as $p):?><option value="<?=$p['id']?>" <?=$profileId===$p['id']?'selected':''?>><?=h($p['printer_code'].' — '.$p['profile_name'])?></option><?php endforeach;?></select></label></form></div>
<?php if($profile['id'] && !empty($profile['firmware_package_id'])):?><form method="post" class="refill-bar"><input type="hidden" name="action" value="refill_profile"><input type="hidden" name="profile_id" value="<?=$profile['id']?>"><label>Detected printer model<select name="refill_model"><option value="auto">Auto-detect from OTA platform</option><option value="a1-mini">A1 mini (n1)</option><option value="a1">A1</option><option value="p1p">P1P</option><option value="p1s">P1S</option><option value="x1c">X1 Carbon</option><option value="h2d">H2D</option></select></label><button class="btn primary" name="overwrite_known" value="0">Auto-fill blank parameters</button><button class="btn" name="overwrite_known" value="1">Refresh model parameters</button><span class="muted small">Use Refresh when this project was imported before platform alias detection was added.</span></form><?php endif;?>
<form method="post" class="profile-form"><input type="hidden" name="action" value="save_profile"><input type="hidden" name="profile_id" value="<?=$profile['id']?>"><input type="hidden" name="firmware_package_id" value="<?=h($profile['firmware_package_id']??'')?>">
<div class="project-toolbar"><span class="tag">Bambu research project</span><?php if(!empty($profile['firmware_package_id'])):?><span class="tag fw-link">OTA #<?=h($profile['firmware_package_id'])?></span><?php endif;?></div><div class="hardware-grid"><label>Printer / platform<input name="printer_code" value="<?=val($profile,'printer_code')?>" placeholder="P1S, X1C, A1, H2D, n2s…" required></label><label>Profile name<input name="profile_name" value="<?=val($profile,'profile_name')?>" placeholder="Observed from firmware 01.08.00"></label><label>Evidence confidence<select name="confidence"><?php foreach(['unknown','inferred','observed','documented','verified'] as $x):?><option <?=$profile['confidence']===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select></label></div>
<h3>MACHINE</h3><div class="grid three"><label>Machine name<input name="machine_name" value="<?=val($profile,'machine_name')?>"></label><label>Kinematics<select name="kinematics"><?php foreach(['CoreXY','Cartesian','Delta','Unknown'] as $x):?><option <?=$profile['kinematics']===$x?'selected':''?>><?=$x?></option><?php endforeach;?></select></label><label>Connectivity<input name="connectivity" value="<?=val($profile,'connectivity')?>" placeholder="WiFi / Ethernet / USB"></label></div>
<h3>GEOMETRY</h3><div class="grid three"><label>X travel (mm)<?php num($profile,'x_travel',0,1000);?></label><label>Y travel (mm)<?php num($profile,'y_travel',0,1000);?></label><label>Z height (mm)<?php num($profile,'z_travel',0,1000);?></label></div>
<h3>SPEED</h3><div class="grid two"><label>Max speed XY (mm/s)<?php num($profile,'max_speed_xy',0,2000);?></label><label>Max acceleration (mm/s²)<?php num($profile,'max_acceleration',0,100000);?></label></div>
<h3>MOTION</h3><p class="critical-note">Critical firmware values use tri-state direction controls. Unknown is never converted to Normal or Inverted.</p><div class="motion-grid"><?php foreach(['x'=>'X','y'=>'Y','z'=>'Z','z2'=>'Z2','e0'=>'E0','e1'=>'E1','e2'=>'E2','e3'=>'E3'] as $k=>$label):?><div class="motion-row"><label>Steps/mm <?=$label?><?php num($profile,'steps_'.$k,0,10000);?></label><label>Direction <?=$label?><select name="direction_<?=$k?>"><?php foreach(['unknown'=>'Unknown','normal'=>'Normal','inverted'=>'Inverted'] as $dv=>$dl):?><option value="<?=$dv?>" <?=($profile['direction_'.$k]??'unknown')===$dv?'selected':''?>><?=$dl?></option><?php endforeach;?></select></label></div><?php endforeach;?></div>
<h3>STEPPER DRIVERS</h3><div class="grid four"><?php foreach(['x'=>'X','y'=>'Y','z'=>'Z','z2'=>'Z2','e0'=>'E0','e1'=>'E1','e2'=>'E2','e3'=>'E3'] as $k=>$label):?><label><?=$label?> motor current (mA)<?php num($profile,'current_'.$k,0,5000);?></label><?php endforeach;?></div><div class="grid three"><label>Microsteps<?php num($profile,'microsteps',1,256,1);?></label><label>Extruder count<?php num($profile,'extruder_count',0,8,1);?></label><label>Nozzle diameter (mm)<?php num($profile,'nozzle_diameter',0.1,2,0.05);?></label></div>
<h3>THERMAL</h3><div class="grid three"><label>Hotend max temp (°C)<?php num($profile,'hotend_max_temp',0,600);?></label><label>Bed max temp (°C)<?php num($profile,'bed_max_temp',0,250);?></label><label>Chamber max temp (°C)<?php num($profile,'chamber_max_temp',0,150);?></label></div>
<h3>PROBE & EVIDENCE</h3><div class="grid two"><label>Bed probe / leveling system<input name="bed_probe" value="<?=val($profile,'bed_probe')?>" placeholder="Load cell, lidar, inductive, unknown"></label><label>Source<input name="source" value="<?=val($profile,'source')?>" placeholder="OTA filename, manifest, OpenBL, measurement…"></label></div><label>Research notes<textarea name="notes" rows="4"><?=val($profile,'notes')?></textarea></label><div class="actions"><button class="btn primary" name="save_mode" value="update">Save project</button><?php if($profile['id']):?><button class="btn" name="save_mode" value="copy">Save as new project</button><?php endif;?></div>
<div class="evidence-editor"><h3>CRITICAL PARAMETER EVIDENCE</h3><p class="muted">Only Measured, Extracted, or Verified values satisfy build readiness. Every critical value retains its own provenance.</p><div class="evidence-table"><?php foreach(PrinterProfiles::criticalFields() as $ef):$er=$evidence[$ef]??['evidence_state'=>'unknown','source'=>'','detail'=>''];?><div class="evidence-row"><strong><?=h(str_replace('_',' ',strtoupper($ef)))?></strong><select name="evidence_<?=$ef?>"><?php foreach(['unknown','inferred','observed','documented','measured','extracted','verified'] as $st):?><option value="<?=$st?>" <?=$er['evidence_state']===$st?'selected':''?>><?=$st?></option><?php endforeach;?></select><input name="evidence_source_<?=$ef?>" value="<?=h($er['source'])?>" placeholder="Source / instrument / component"><input name="evidence_detail_<?=$ef?>" value="<?=h($er['detail'])?>" placeholder="Offset, method, test conditions, notes"></div><?php endforeach;?></div></div>
</form><?php if($profile['id']):?><div class="actions secondary-actions"><form method="post"><input type="hidden" name="action" value="export_project"><input type="hidden" name="profile_id" value="<?=$profile['id']?>"><button class="btn">Export research project JSON</button></form><?php if(!empty($profile['firmware_package_id'])):?><form method="post"><input type="hidden" name="action" value="download_official"><input type="hidden" name="package_id" value="<?=$profile['firmware_package_id']?>"><button class="btn">Download original signed OTA</button></form><?php endif;?></div><?php endif;?></section>
<section id="pipeline"><div class="section-title"><div><h2>Stock A1 mini build pipeline</h2><p class="muted">RAM probing is available before the active motor, thermal, persistent-flash, and SD deployment stages. Critical operating values still require measured, extracted, or verified evidence.</p></div><span class="badge <?=$stockStatus['probe_ready']?'ready':'blocked'?>"><?=$stockStatus['probe_ready']?'PROBE READY':'BLOCKED'?></span></div><div class="stage-grid"><?php foreach($stockStatus['stages'] as $stage):?><article class="stage-card <?=h($stage['state'])?>"><strong><?=h($stage['name'])?></strong><span><?=h(strtoupper($stage['state']))?></span><small><?=h($stage['reason'])?></small></article><?php endforeach;?></div><h3>Parameter evidence gate</h3><?php if(!$readiness['ready']):?><div class="blocked-list"><strong>Missing or insufficient evidence:</strong><ul><?php foreach($readiness['missing'] as $m):?><li><code><?=h($m['field'])?></code> — value <?=h(($m['value']===null||$m['value']==='')?'missing':$m['value'])?>; evidence <?=h($m['state'])?></li><?php endforeach;?></ul></div><?php else:?><div class="ok">All required values have acceptable evidence. This status validates the research profile only; signed Bambu deployment still requires an authorized build and signing path.</div><?php endif;?></section>
<section id="stock-builder"><div class="section-title"><div><h2>A1 mini stock-board firmware creator</h2><p class="muted">Generate a local CAPCOM project bundle for the installed SPINTROL SPC2168 mainboard controller and SPC1168 toolhead controller. The first executable stage is a read-only RAM probe, not an SKR/Klipper build and not a modified Bambu OTA.</p></div><span class="badge experimental">LOCAL RESEARCH</span></div>
<?php if(!$profile['id']):?><div class="blocked-list">Save or open an A1 mini / n1 project before generating a stock-board research bundle.</div><?php else:?>
<div class="target-grid"><article><span class="tag">MAINBOARD MC</span><h3>SPINTROL SPC2168APE80</h3><p>Dual Cortex-M4, up to 200 MHz, 512 KiB flash, 80 KiB SRAM, 16 PWM outputs, 20-channel 14-bit ADC, SWD/JTAG, UART ISP.</p><code>Flash 0x10000000 · SRAM 0x20000000</code></article><article><span class="tag">TOOLHEAD TH</span><h3>SPINTROL SPC1168APE48</h3><p>Cortex-M4 toolhead controller observed on N1_EXTRU_V5. The supplied first-stage probe runs entirely from SRAM and does not touch outputs or flash.</p><code>Flash 0x10000000 · SRAM 0x20000000</code></article></div>
<div class="lab-warning"><strong>Probe contract:</strong> the prebuilt probe writes only an eight-word report to <code>0x20003C00</code>. It does not configure GPIO, PWM, motors, heaters, fans, flash, option/configuration words, or protection state.</div>
<form method="post" class="profile-form builder-form"><input type="hidden" name="action" value="generate_stock_probe"><input type="hidden" name="profile_id" value="<?=$profile['id']?>">
<h3>OUTPUT BUNDLE</h3><div class="grid three"><label>Main controller<input value="Stock SPC2168APE80" readonly></label><label>Toolhead controller<input value="Stock SPC1168APE48" readonly></label><label>First stage<input value="RAM-only probe + source" readonly></label></div>
<h3>KNOWN DEBUG PINS — MCU PACKAGE ONLY</h3><div class="pin-table"><table><thead><tr><th>Board</th><th>Signal</th><th>MCU pin</th><th>PCB pad</th><th>Status</th></tr></thead><tbody><tr><td>MC / SPC2168 LQFP80</td><td>XRSTn</td><td>68</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>MC / SPC2168 LQFP80</td><td>TRSTn</td><td>69</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>MC / SPC2168 LQFP80</td><td>SWCLK / GPIO48</td><td>70</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>MC / SPC2168 LQFP80</td><td>SWDIO / GPIO49</td><td>71</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>TH / SPC1168 LQFP48</td><td>SWDIO / GPIO38</td><td>44</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>TH / SPC1168 LQFP48</td><td>SWCLK / GPIO39</td><td>45</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>TH / SPC1168 LQFP48</td><td>TRSTn</td><td>46</td><td>Unmapped</td><td>Datasheet only</td></tr><tr><td>TH / SPC1168 LQFP48</td><td>XRSTn</td><td>47</td><td>Unmapped</td><td>Datasheet only</td></tr></tbody></table></div>
<label class="ack"><input type="checkbox" name="research_ack" value="yes" required> I understand this bundle targets the installed A1 mini boards, the probes must be loaded into SRAM through verified SWD wiring, and I will not use unlock, erase, or protection-changing commands.</label>
<div class="actions"><button class="btn primary">Generate stock A1 mini firmware-lab ZIP</button></div></form><?php endif;?></section>
<section id="hardware"><h2>A1 mini hardware lab</h2><p class="muted">Evidence-backed board inventory generated from the imported OTA and supplied high-resolution board photographs. Connector functions remain unknown until traced or measured.</p><div class="hardware-cards"><?php foreach($hardware as $hw):?><article class="hw-card"><div><span class="tag"><?=h($hw['printer_code'])?></span> <span class="tag"><?=h($hw['board_role'].' '.$hw['board_revision'])?></span></div><h3><?=h($hw['component_role'])?></h3><strong><?=h(trim($hw['manufacturer'].' '.$hw['part_number']))?></strong><p>Marking: <code><?=h($hw['marking']?:'—')?></code></p><p>Evidence: <?=h($hw['evidence_state'])?></p><small><?=h($hw['source'])?></small></article><?php endforeach;?></div><div class="lab-warning">Do not connect an ST-Link until voltage, ground, SWDIO, SWCLK, and reset pads are independently confirmed with continuity and voltage measurements. HotFetched will store the measurements and pin evidence without assuming a debug pinout.</div></section>
<section id="extraction"><h2>Automatic extraction status</h2><p class="muted">HotFetched fills values only when they come from a selected documented model preset or from data actually decoded from the OTA. Proprietary motion calibration, current limits, direction flags, and signing material may not be present as readable manifest fields.</p><div class="extraction-grid"><?php foreach([
'Machine & geometry'=>['machine_name','kinematics','x_travel','y_travel','z_travel'],
'Speed & thermal'=>['max_speed_xy','max_acceleration','hotend_max_temp','bed_max_temp','chamber_max_temp'],
'Low-level motion'=>['steps_x','steps_y','steps_z','steps_e0','current_x','current_y','current_z','current_e0','microsteps']
] as $group=>$keys):$known=0;foreach($keys as $key)if(($profile[$key]??'')!==''&&($profile[$key]??null)!==null)$known++;?><div class="extract-card"><strong><?=h($group)?></strong><span><?=$known?> / <?=count($keys)?> populated</span><small><?= $known===count($keys)?'Available':'Unknown fields remain blank' ?></small></div><?php endforeach;?></div></section>
<section id="firmware"><h2>Firmware library</h2><p class="muted">Every imported release is retained for later component and parameter comparison.</p><table><thead><tr><th>ID</th><th>Printer</th><th>Version</th><th>Build</th><th>Components</th><th>SHA-256</th><th>Imported</th></tr></thead><tbody><?php foreach($packages as $p):?><tr><td><?=$p['id']?></td><td><?=h($p['printer_code']?:'unknown')?></td><td><?=h($p['version']?:'unknown')?></td><td><?=h($p['build_stamp']?:'—')?></td><td><?=$p['component_count']?></td><td><code><?=h(substr($p['sha256'],0,16))?>…</code></td><td><?=h($p['imported_at'])?></td></tr><?php endforeach;?></tbody></table></section>
<section id="compare"><h2>Compare firmware releases</h2><form method="get"><select name="a" required><option value="">Release A</option><?php foreach($packages as $p):?><option value="<?=$p['id']?>" <?=$aid===$p['id']?'selected':''?>>#<?=$p['id']?> <?=h($p['printer_code'].' '.$p['version'])?></option><?php endforeach;?></select><select name="b" required><option value="">Release B</option><?php foreach($packages as $p):?><option value="<?=$p['id']?>" <?=$bid===$p['id']?'selected':''?>>#<?=$p['id']?> <?=h($p['printer_code'].' '.$p['version'])?></option><?php endforeach;?></select><button>Compare</button></form><?php if($compare):?><table><thead><tr><th>Component key</th><th>Status</th><th>A version</th><th>B version</th><th>Size delta</th></tr></thead><tbody><?php foreach($compare as $r):$d=($r['b']['bytes']??0)-($r['a']['bytes']??0);?><tr><td><?=h($r['key'])?></td><td class="status <?=h($r['status'])?>"><?=h($r['status'])?></td><td><?=h($r['a']['version']??'—')?></td><td><?=h($r['b']['version']??'—')?></td><td><?=$d>=0?'+':''?><?=$d?></td></tr><?php endforeach;?></tbody></table><?php endif;?></section>
<section id="boards"><h2>Board and firmware evidence</h2><p class="muted">This table separates documented hardware facts from values only observed in OTA filenames.</p><table><thead><tr><th>Printer/platform</th><th>Role</th><th>Revision</th><th>MCU</th><th>Evidence</th><th>Confidence</th><th>Source</th></tr></thead><tbody><?php foreach($boards as $b):?><tr><td><?=h($b['printer_code'])?></td><td><?=h($b['board_role'])?></td><td><?=h($b['board_revision']?:'—')?></td><td><?=h($b['mcu']?:'unknown')?></td><td><pre><?=h(json_encode(json_decode($b['parameters_json'],true),JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES))?></pre></td><td><?=h($b['confidence'])?></td><td><?=h($b['source'])?></td></tr><?php endforeach;?></tbody></table></section>
<footer>Private research and education only. Target: installed A1 mini SPC2168 mainboard and SPC1168 toolhead. Official Bambu OTAs remain unchanged; no public upload or replacement-controller output.</footer></main></body></html>
